# Generated by Django 5.0.6 on 2024-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('job_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(max_length=10)),
                ('created_by_admin', models.CharField(max_length=255)),
            ],
        ),
    ]
