# Generated by Django 5.0.6 on 2024-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
